### ISSUE TITLE
error TS1016: A required parameter cannot follow an optional parameter.

### ISSUE THREAD

**Issue by zhangningwin** [LRagji/redis-streams-broker#13]
error TS1016: A required parameter cannot follow an optional parameter.
Change the parameter failOnMaxMessageCount to optional or put it in front

This is a compile time error

yarn run v1.22.19
$ tsc -p tsconfig.build.json
node_modules/redis-streams-broker/index.d.ts:4:64 - error TS1016: A required parameter cannot follow an optional parameter.

4     publish(payload: any, maximumApproximateMessages?: number, failOnMaxMessageCount: boolean): Promise<string>;
                                                                 ~~~~~~~~~~~~~~~~~~~~~

Found 1 error in node_modules/redis-streams-broker/index.d.ts:4

**Comment by LRagji** [comment]
@zhangningwin Thanks,
Its a broken def file, will fix it by EOD both parameters are defaulted
