### ISSUE TITLE
scripts folder cannot be found when used from npm

### ISSUE THREAD

**Issue by jkosters** [LRagji/redis-streams-broker#4]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `redis-streams-broker@0.0.11` for the project I'm working on.

When the module is loaded from npm the scripts dir cannot be found. This is because of different a different current working dir. Simple take any of the examples and try to run them from a clean npm init and you will see.

** reproduction steps **
```
yarn init
yarn add redist-stream-broker ioredis

...copy any of the examples in the index.js...

yarn .
```

** The fix **
The fix is to search from the directory where the file exists instead of the cwd.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/redis-streams-broker/index.js b/node_modules/redis-streams-broker/index.js
index 7c614b8..7f7981b 100644
--- a/node_modules/redis-streams-broker/index.js
+++ b/node_modules/redis-streams-broker/index.js
@@ -1,3 +1,4 @@
+const path = require("path");
 const shortid = require("shortid");
 const Scripto = require("redis-scripto");
 
@@ -19,7 +20,7 @@ class StreamChannelBroker {
         this._acknowledgeMessage = this._destroyingCheckWrapper(this._acknowledgeMessage.bind(this));
         this._unsubscribe = this._destroyingCheckWrapper(this._unsubscribe.bind(this), false);
         this._groupPendingSummary = this._destroyingCheckWrapper(this._groupPendingSummary.bind(this), false);
-        this._scriptManager.loadFromDir('./scripts');
+        this._scriptManager.loadFromDir(path.join(__dirname, 'scripts'));
     }
 
     _destroyingCheckWrapper(fn, async = true) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by LRagji** [comment]
@jkosters Thanks for the issue report, will surely look into this in next 48 hrs and have a release for this if required...

**Comment by LRagji** [comment]
Fixed in https://github.com/LRagji/redis-streams-broker/releases/tag/v0.0.12
