### ISSUE TITLE
Replace deprecated hard dependency `shortid`

### ISSUE THREAD

**Issue by micalevisk** [LRagji/redis-streams-broker#5]
https://github.com/LRagji/redis-streams-broker/blob/8182eaa6bdb464439a56a57ffb40c6a7cbf2d29d/package.json#L35
https://github.com/LRagji/redis-streams-broker/blob/8182eaa6bdb464439a56a57ffb40c6a7cbf2d29d/index.js#L46
https://github.com/LRagji/redis-streams-broker/blob/016db54f8d6668b5978fa87bd68e79bf188ab626/readme.md#L72

![image](https://user-images.githubusercontent.com/13461315/131267625-b1c406be-1f74-4e54-a5d1-0c62e57ab669.png)

You could use the lib [nanoid](https://github.com/ai/nanoid)

**Comment by micalevisk** [comment]
btw you could replace `redis-scripto` with `redis-scripto2` (which is an up-to-date fork) due to this security issue: https://github.com/arunoda/node-redis-scripto/pull/9

**Comment by LRagji** [comment]
Thanks give me some time will check and upgrade...
